2023-02-21 12:08:19,787 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:18:01,390 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:18:21,979 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:18:37,176 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:24:12,613 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:24:58,307 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:25:42,983 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:25:54,053 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:32:29,280 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:43:10,648 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
2023-02-23 08:43:19,284 ERROR: Exception on / [GET] [in /opt/anaconda3/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/routes.py", line 30, in index
    return render_template("index.html", title='Home Page', form=form,
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/templates/index.html", line 20, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2023-02-23 08:43:19,291 ERROR: Exception on / [GET] [in /opt/anaconda3/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/routes.py", line 30, in index
    return render_template("index.html", title='Home Page', form=form,
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/templates/index.html", line 20, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2023-02-23 08:43:29,155 ERROR: Exception on /index [GET] [in /opt/anaconda3/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/anaconda3/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/routes.py", line 30, in index
    return render_template("index.html", title='Home Page', form=form,
  File "/opt/anaconda3/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/templates/index.html", line 20, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2023-02-23 08:44:51,109 INFO: Microblog startup [in /Users/kavolkova/Desktop/Code/microblog_repo/microblog/app/__init__.py:44]
